export interface user{
    userId:string,
    email:string,
    userName:string,
    Name:string,
    bio:string,
    X:string,
    snapchat:string,
    facebook:string,
    instagram:string,
    whatsapp:string,
    tiktok:string,
    location: string,
    photoUrl:string,
    bgUrl:string,
}